<?php
$listarazasperros =
    [
        'Mestizo',
        'Airedale terrier',
        'Akita Americano',
        'Akita Inu',
        'Alano español',
        'Alaskan malamute',
        'American bully',
        'American Hairless terrier',
        'American Staffordshire Terrier',
        'Antiguo Perro Pastor Inglés',
        'Bóxer',
        'Bardino (Perro majorero)',
        'Basenji',
        'Basset hound',
        'Beagle',
        'Beauceron',
        'Bichón maltés',
        'Bichon frisé',
        'Bloodhound',
        'Bodeguero Andaluz',
        'Border collie',
        'Borzoi',
        'Boston terrier',
        'Braco alemán de pelo corto',
        'Braco alemán de pelo duro',
        'Braco de Auvernia',
        'Braco de Saint Germain',
        'Braco de Weimar',
        'Braco francés',
        'Braco húngaro',
        'Braco italiano',
        'Braco tirolés',
        'Bull Terrier',
        'Bulldog americano',
        'Bulldog francés',
        'Bulldog inglés',
        'Bullmastiff',
        'Cão da Serra da Estrela',
        'Cão da Serra de Aires',
        'Cão de Agua Português',
        'Cão de Castro Laboreiro',
        'Cão de Fila de São Miguel',
        'Can de palleiro',
        'Caniche',
        'Carlino',
        'Cavalier King Charles spaniel',
        'Chihuahua',
        'Chow chow',
        'Clumber spaniel',
        'Cocker spaniel americano',
        'Cocker spaniel inglés',
        'Collie',
        'Collie barbudo',
        'Crestado Chino',
        'Dálmata',
        'Dachshund',
        'Dobermann',
        'Dogo argentino',
        'Dogo alemán',
        'Dogo de burdeos',
        'Dogo guatemalteco',
        'Flat-Coated Retriever',
        'Fox Terrier',
        'Galgo afgano',
        'Galgo español',
        'Galgo húngaro',
        'Galgo inglés',
        'Galgo italiano',
        'Gegar colombiano',
        'Golden retriever',
        'Gran danés',
        'Greyhound',
        'Grifón belga',
        'Grifón azul',
        'Husky siberiano',
        'Irish Wolf Hound',
        'Jack Russell Terrier',
        'Keeshond',
        'Kerry blue terrier',
        'Komondor',
        'Kuvasz',
        'Labrador',
        'Lebrel afgano',
        'Lhasa apso',
        'Lobo de saarloos',
        'Maltés',
        'Manchester terrier',
        'Mastín afgano',
        'Mastín del Pirineo',
        'Mastín español',
        'Mastín inglés',
        'Mastín napolitano',
        'Mastín tibetano',
        'Mucuchies',
        'Ovejero magallánico',
        'Pastor alemán',
        'Pastor belga',
        'Pastor blanco suizo',
        'Pastor catalán',
        'Pastor croata',
        'Pastor de los Pirineos',
        'Pastor garafiano',
        'Pastor holandés',
        'Pastor leonés',
        'Pastor mallorquín',
        'Pastor peruano Chiribaya',
        'Pastor vasco',
        'Pekinés',
        'Pembroke Welsh Corgi',
        'Pequeño Lebrel Italiano',
        'Perdiguero de Burgos',
        'Perdiguero francés',
        'Perdiguero portugués',
        'Perro cimarrón uruguayo',
        'Perro de agua americano',
        'Perro de agua español',
        'Perro de agua irlandés',
        'Perro de agua portugués',
        'Perro de Montaña de los Pirineos',
        'Perro dogo mallorquín',
        'Perro esquimal canadiense',
        'Perro pastor de las islas Shetland',
        'Perro peruano sin pelo',
        'Phalène',
        'Pinscher alemán',
        'Pinscher miniatura',
        'Pitbull',
        'Podenco canario',
        'Podenco ibicenco',
        'Podenco portugués',
        'Pointer',
        'Pomerania',
        'Presa canario',
        'Pug',
        'Puli',
        'Rafeiro do Alentejo',
        'Ratonero bodeguero andaluz',
        'Ratonero mallorquín',
        'Ratonero valenciano',
        'Rhodesian Ridgeback',
        'Rottweiler',
        'Sabueso italiano',
        'Sabueso español',
        'Saluki',
        'Samoyedo',
        'San Bernardo',
        'Sato',
        'Schnauzer estándar',
        'Schnauzer gigante',
        'Schnauzer miniatura',
        'Setter gordon',
        'Setter inglés',
        'Setter irlandés',
        'Shar Pei',
        'Shiba Inu',
        'Shih Tzu',
        'Siberian husky',
        'Skye terrier',
        'Spaniel bretón',
        'Spaniel papillón',
        'Spitz alemán',
        'Spitz finlandés',
        'Sussex spaniel',
        'Teckel',
        'Terranova',
        'Terrier alemán',
        'Terrier australiano',
        'Terrier brasileño',
        'Terrier chileno',
        'Terrier escocés',
        'Terrier galés',
        'Terrier irlandés',
        'Weimaraner',
        'West Highland White Terrier',
        'Whippet',
        'Xoloitzcuintle',
        'Yorkshire terrier'
    ];


$listarazasgatos =  [
    "Común Europeo",
    "Africano doméstico",
    "American Curl",
    "American shorthair",
    "American wirehair",
    "Angora turco",
    "Aphrodite-s Giants",
    "Australian Mist",
    "Azul ruso",
    "Bengala",
    "Bobtail japonés",
    "Bombay",
    "Bosque de Noruega",
    "Brazilian Shorthair",
    "British Shorthair",
    "Burmés",
    "Burmilla",
    "California Spangled",
    "Ceylon",
    "Chartreux",
    "Cornish rex",
    "Cymric",
    "Deutsch Langhaar",
    "Devon rex",
    "Don Sphynx",
    "Dorado africano",
    "Europeo común",
    "Gato exótico",
    "German Rex",
    "Habana brown",
    "Himalayo",
    "Khao Manee",
    "Korat",
    "Maine Coon",
    "Maine Tabby",
    "Manx",
    "Mau egipcio",
    "Munchkin",
    "Ocicat",
    "Ojos azules",
    "Oriental",
    "Oriental de pelo largo",
    "Persa",
    "Peterbald",
    "Pixi Bob",
    "Ragdoll",
    "Sagrado de Birmania",
    "Scottish Fold",
    "Selkirk rex",
    "Serengeti",
    "Seychellois",
    "Siamés",
    "Siamés Moderno",
    "Siamés Tradicional",
    "Siberiano",
    "Snowshoe",
    "Sphynx",
    "Tonkinés",
    "Van Turco"
];


?>
